apiVersion: apps/v1
kind: Deployment
metadata:
  name: apriori-cache
spec:
  selector:
    matchLabels:
      app: apriori-cache
  replicas: 1
  template:
    metadata:
      labels:
        app: apriori-cache
    spec:
      containers:
        - name: apriori-cache
          image: redis:6
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: apriori-cache
  labels:
    app: apriori-cache
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: apriori-cache