version: "3"
services:
  db:
    container_name: apriori-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: apriori
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backend/database/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - thesis
    restart: always
  cache:
    container_name: apriori-cache-1
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - thesis
    restart: always
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./backend/monitoring/grafana/grafana-data:/var/lib/grafana
      - ./backend/monitoring/grafana/grafana-data:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=Rahasia123
    depends_on:
      - prometheus
    networks:
      - thesis
    restart: always
  prometheus:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./backend/monitoring/prometheus:/etc/prometheus/
      - ./backend/monitoring/prometheus/prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - "9090:9090"
    restart: always
    networks:
      - thesis
  nsqlookupd:
    image: nsqio/nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd
    networks:
      - thesis
    restart: always
  nsqd:
    image: nsqio/nsq
    ports:
      - "4150:4150"
      - "4151:4151"
    depends_on:
      - nsqlookupd
    command: /nsqd -lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=nsqd
    networks:
      - thesis
    restart: always
  nsqadmin:
    image: nsqio/nsq
    ports:
      - "4171:4171"
    depends_on:
      - nsqlookupd
      - nsqd
    command: /nsqadmin -lookupd-http-address=nsqlookupd:4161
    networks:
      - thesis
    restart: always
  messagebroker:
    container_name: apriori-message-broker
    image: apriori-message-broker:latest
    env_file:
      - ./backend/services/message-service/config/envs/test.env
    ports:
      - "8085:8080"
    restart: always
    depends_on:
      - nsqlookupd
    networks:
      - thesis
  adapter:
    container_name: apriori-adapter
    image: apriori-adapter:latest
    env_file:
      - ./backend/adapter/config/envs/test.env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - nsqlookupd
    networks:
      - thesis
  apriori:
    container_name: apriori-apriori
    image: apriori-apriori:latest
    env_file:
      - ./backend/services/apriori-service/config/envs/test.env
    ports:
      - "50050:50050"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  category:
    container_name: apriori-category
    image: apriori-category:latest
    env_file:
      - ./backend/services/category-service/config/envs/test.env
    ports:
      - "50051:50051"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  comment:
    container_name: apriori-comment
    image: apriori-comment:latest
    env_file:
      - ./backend/services/comment-service/config/envs/test.env
    ports:
      - "50052:50052"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  notification:
    container_name: apriori-notification
    image: apriori-notification:latest
    env_file:
      - ./backend/services/notification-service/config/envs/test.env
    ports:
      - "50053:50053"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  password:
    container_name: apriori-password-reset
    image: apriori-password-reset:latest
    env_file:
      - ./backend/services/password-reset-service/config/envs/test.env
    ports:
      - "50054:50054"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  payment:
    container_name: apriori-payment
    image: apriori-payment:latest
    env_file:
      - ./backend/services/payment-service/config/envs/test.env
    ports:
      - "50055:50055"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  product:
    container_name: apriori-product
    image: apriori-product:latest
    env_file:
      - ./backend/services/product-service/config/envs/test.env
    ports:
      - "50056:50056"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  transaction:
    container_name: apriori-transaction
    image: apriori-transaction:latest
    env_file:
      - ./backend/services/transaction-service/config/envs/test.env
    ports:
      - "50057:50057"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  order:
    container_name: apriori-user-order
    image: apriori-user-order:latest
    env_file:
      - ./backend/services/user-order-service/config/envs/test.env
    ports:
      - "50058:50058"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis
  user:
    container_name: apriori-user
    image: apriori-user:latest
    env_file:
      - ./backend/services/user-service/config/envs/test.env
    ports:
      - "50059:50059"
    restart: always
    depends_on:
      - db
      - cache
      - messagebroker
      - adapter
    networks:
      - thesis

networks:
  thesis:
    driver: bridge
