version: "3"
services:
  db:
    container_name: apriori-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: apriori
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./backend/database/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - thesis
    restart: always
  cache:
    container_name: apriori-cache
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - thesis
    restart: always

networks:
  thesis:
    driver: bridge