main:
	go run adapter/main.go

apriori:
	go run services/apriori-service/main.go

category:
	go run services/category-service/main.go

comment:
	go run services/comment-service/main.go

notification:
	go run services/notification-service/main.go

password:
	go run services/password-reset-service/main.go

payment:
	go run services/payment-service/main.go

product:
	go run services/product-service/main.go

transaction:
	go run services/transaction-service/main.go

order:
	go run services/user-order-service/main.go

user:
	go run services/user-service/main.go

message:
	go run services/message-service/main.go