apiVersion: apps/v1
kind: Deployment
metadata:
  name: apriori-adapter
  labels:
    app: apriori-adapter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apriori-adapter
  template:
    metadata:
      labels:
        app: apriori-adapter
    spec:
      containers:
        - name: apriori-adapter
          image: arvians/apriori-adapter:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: apriori-adapter
spec:
  selector:
    app: apriori-adapter
  ports:
    - port: 8080
      nodePort: 30080
  type: NodePort