apiVersion: apps/v1
kind: Deployment
metadata:
  name: apriori-apriori
  labels:
    app: apriori-apriori
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apriori-apriori
  template:
    metadata:
      labels:
        app: apriori-apriori
    spec:
      containers:
        - name: apriori-apriori
          image: arvians/apriori-apriori:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 50050
          envFrom:
            - configMapRef:
                name: env-prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: apriori-apriori
spec:
  selector:
    app: apriori-apriori
  ports:
    - port: 50050
      targetPort: 50050
