apiVersion: apps/v1
kind: Deployment
metadata:
  name: apriori-category
  labels:
    app: apriori-category
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apriori-category
  template:
    metadata:
      labels:
        app: apriori-category
    spec:
      containers:
        - name: apriori-category
          image: apriori-category:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 50051
          envFrom:
            - configMapRef:
                name: env-prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: apriori-category
spec:
  selector:
    app: apriori-category
  ports:
    - port: 50051
      targetPort: 50051
