apiVersion: apps/v1
kind: Deployment
metadata:
  name: apriori-comment
  labels:
    app: apriori-comment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apriori-comment
  template:
    metadata:
      labels:
        app: apriori-comment
    spec:
      containers:
        - name: apriori-comment
          image: arvians/apriori-comment:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 50052
          envFrom:
            - configMapRef:
                name: env-prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: apriori-comment
spec:
  selector:
    app: apriori-comment
  ports:
    - port: 50052
      targetPort: 50052
