apiVersion: apps/v1
kind: Deployment
metadata:
  name: apriori-password-reset
  labels:
    app: apriori-password-reset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apriori-password-reset
  template:
    metadata:
      labels:
        app: apriori-password-reset
    spec:
      containers:
        - name: apriori-password-reset
          image: arvians/apriori-password-reset:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 50054
          envFrom:
            - configMapRef:
                name: env-prod-config
---
apiVersion: v1
kind: Service
metadata:
  name: apriori-password-reset
spec:
  selector:
    app: apriori-password-reset
  ports:
    - port: 50054
      targetPort: 50054
